### ISSUE TITLE
macOS binary depends on crystal dependencies

### ISSUE THREAD

**Issue by chaychoong** [coverallsapp/coverage-reporter#1]
### How to replicate
1. Download the binary onto a fresh machine and run it

```
❯ coveralls -h
dyld: Library not loaded: /usr/local/opt/libyaml/lib/libyaml-0.2.dylib
  Referenced from: /usr/local/bin/coveralls
  Reason: image not found
```

2. Run `brew install crystal`
3. Issue disappears

### Related issues

https://github.com/crystal-lang/crystal/issues/5994

### Proposed solution

Distribute the macOS binary with `homebrew` and include `libyaml` as a dependency

**Comment by mrexox** [comment]
Hey! Now coveralls-reporter can be installed from homebrew. Please, try this:

```bash
brew tap coverallsapp/coveralls
brew install coveralls
```

This is the primary method of installation for coveralls-reporter on macOS now. Write back if you face any issues!
