### ISSUE TITLE
Is there a way to lock in a specific version of coveralls on linux, when downloading

### ISSUE THREAD

**Issue by snackattas** [coverallsapp/coverage-reporter#111]
### :zap: Summary

The linux install instructions are just do `curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C /usr/local/bin`

But shouldn't there be a way to specify what version you want to pull down? what if coveralls accidentally introduces a breaking change, every docker build doing this curl, would bring in the new version, since they can't lock it in

**Comment by afinetooth** [comment]
Yes, this is one way that I am aware of:

```
curl -L [URL_of_the_v0.6.5_binary] | tar -xz -C /usr/local/bin
```

So let's say you wanted to install `v0.6.5`:

```
curl -L https://github.com/coverallsapp/coverage-reporter/releases/download/v0.6.5/coveralls-linux.tar.gz | tar -xz -C /usr/local/bin
```

**Comment by snackattas** [comment]
Thanks! That works
