### ISSUE TITLE
If you use coveralls-python, which gives you CLI tools coverage and coveralls...the name coveralls conflicts with this tool

### ISSUE THREAD

**Issue by snackattas** [coverallsapp/coverage-reporter#112]
### :zap: Summary

I am confused how you are supposed to use this coverage uploader, with the python package, for example. Since you still need the python package, to generate the coverage report (which is then uploaded by this tool)

coveralls-python adds the cli tool `coveralls` which conflicts with the name of this one, which is also `coveralls`

**Comment by afinetooth** [comment]
Hi @snackattas we don't recommend using the Coverage Reporter with the `coveralls-python` integration. Both are Coveralls integrations in their own right that should be used separately. We support and maintain the [official integration](https://docs.coveralls.io/integrations#official-integrations), known as the [Coveralls Universal Coverage Reporter](https://github.com/coverallsapp/coverage-reporter). The [coveralls-python integration](https://github.com/TheKevJames/coveralls-python), and well-maintained Coveralls language integration, is maintained by [TheKevJames](https://github.com/TheKevJames).

I replied to your separate support request to support@coveralls.io about this, but will repeat what I said there if you wish to use the [Coverage Reporter](https://github.com/coverallsapp/coverage-reporter):

### Tip for using the Coverage Reporter with Python:
Right now, our support for [pytest-cov format ](https://github.com/coverallsapp/coverage-reporter#:~:text=Pytest%2DCov%20(%F0%9F%A7%AA%20beta)%20%2D%20python)(and the native coverage.py report in SQLite format; aka. the `.coverage` file) is in beta and we have received some bug reports on it. 

**So for now we recommend this strategy for using the Coverage Reporter with Python**:

1. When you generate your python coverage reports with coverage.py in CI, export your coverage report in its natively supported XML format (Cobertura XML). To do that, you can use one of several possible commands, the simplest being this one:
  - `coverage xml` which is [documented here](https://coverage.readthedocs.io/en/7.4.3/cmd.html#cmd-xml). This exports your coverage report in Cobertura XML format.
2. Configure the integration as normal for your CI service, but make sure to specify the coverage report format as `cobertura`. Here's how to do that if you are using the Coverage Reporter directly:
  - `coverage report --format=cobertura` which is [documented here](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#examples:~:text=For%20more%20options%20see%20coveralls%20%2D%2Dhelp), or when you invoke the Coverage Reporter's `coveralls --help` command.

That will make sure Coverage Reporter parses the XML format report, which it does very accurately, and currently more accurately than it can parse the default coverage.py (aka. `.coverage`) report.

**Comment by snackattas** [comment]
Thanks for the recommendations!
