### ISSUE TITLE
running coveralls --done causes SSL certificate error

### ISSUE THREAD

**Issue by tchiaspko** [coverallsapp/coverage-reporter#12]
env: amazon linux 2022 

coveralls --done 

```

⭐️ Calling parallel done webhook: https://coveralls.io/webhook
---
⛑ Debug Output:
{"repo_token":"xxxxxxxx","payload":{"build_num":"10","status":"done"}}
Unhandled exception: SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (OpenSSL::SSL::Error)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

**Comment by mrexox** [comment]
Hey @tchiaspko! Thank you for reporting an issue. I've got a few questions to better understand the problem:

1. Does it fail always or only one time?
2. What is the `coveralls` version? Does the latest version still fail?

**Comment by tchiaspko** [comment]
1. It fails all the time. I have switched to use curl method to finish the job to avoid this issue
2. 0.2.3
[jenkins@ip-172-16-80-39 ~]$ ./coveralls --version
0.2.3
[jenkins@ip-172-16-80-39 ~]$

**Comment by mrexox** [comment]
Do you have some environment variables configured? Can you share some of them (excluding secret content of course)?

Just as a workaround I can suggest trying adding `COVERALLS_ENDPOINT=https://coveralls.io` env and try one more time (we [skip ssl checks](https://github.com/coverallsapp/coverage-reporter/blob/master/src/coverage_reporter/api/webhook.cr#L29) when it is provided)

**Comment by tchia04** [comment]
Actually the version that had the issue was  
  v0.1.8

I have tried it with 0.2.3 and it works now with and without setting COVERALLS_ENDPOINT
