### ISSUE TITLE
Coverall 0.6.11 stops parsing lcov files created by `bazel`

### ISSUE THREAD

**Issue by mpatou** [coverallsapp/coverage-reporter#127]
### What was wrong?

We use `bazel` to generate coverage file with `bazel coverage --combined_report=lcov  //go/...`, it was working with 0.6.10. As far as I can tell the format was fine there because we can see the report and also `genhtml` is fine with the file.

### Logs

```
coveralls --format=lcov --debug -f /data/home/mpatou/.cache/bazel/_bazel_mpatou/aabbcc/execroot/rs_monorepo/bazel-out/k8-fastbuild/testlogs/go/svc/server/server_test/coverage.dat 
```
 Got:
 
  v0.6.11

✏️ Forced coverage format: lcov
📄 Using coverage file: /data/home/mpatou/.cache/bazel/_bazel_mpatou/aabbcc/execroot/rs_monorepo/bazel-out/k8-fastbuild/testlogs/go/svc/server/server_test/coverage.dat
⚠️ Coverage reporter does not yet know how to process this file: /data/home/mpatou/.cache/bazel/_bazel_mpatou/aabbcc/execroot/rs_monorepo/bazel-out/k8-fastbuild/testlogs/go/svc/server/server_test/coverage.dat
⏱️ Report parsing: 00:00:00.000032771
🚨 Nothing to report

**Comment by rouault** [comment]
I ge the same error with GDAL builds that have just started to fail. Cf https://github.com/OSGeo/gdal/actions/runs/9163147706/job/25191612186:
```
Run coveralls report      --format lcov build-coverage/gdal_filtered.info 
⚠️ Coverage reporter does not yet know how to process this file: build-coverage/gdal_filtered.info
 
⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠀⠀⠀⣼⣿⣧⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀⢠⣿⣿⣿⠿⣿⣿⣿⡄⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀⠀⠀
 
  v0.6.11
```

**Comment by afinetooth** [comment]
@mpatou @rouault Thanks. We're looking into this. Will update you here.

**Comment by mrc0mmand** [comment]
I just noticed the same issue with our systemd reports. It seems that since https://github.com/coverallsapp/coverage-reporter/commit/8d5f1d4d1425ac02b0925646ee3020b170c481cb `coveralls` now validates the filename even if `--format=` is used, but I can't seem to make it work even if I rename the coverage file:

```
# lcov --summary everything.lcov 
Reading tracefile everything.lcov.
Summary coverage rate:
  source files: 1808
  lines.......: 70.9% (282215 of 398294 lines)
  functions...: 88.3% (20360 of 23046 functions)
Message summary:
  no messages were reported
# coveralls --debug --format=lcov report everything.lcov 
 
...
 
  v0.6.11

✏ Forced coverage format: lcov
📄 Using coverage file: everything.lcov
☝ Detected coverage format: lcov - everything.lcov
⏱ Report parsing: 00:00:00.202190375
🚨 Nothing to report

# coveralls --debug report everything.lcov 
 
...
 
  v0.6.11

📄 Using coverage file: everything.lcov
☝ Detected coverage format: lcov - everything.lcov
⏱ Report parsing: 00:00:00.206965709
🚨 Nothing to report

```

I find it a bit weird that forcing a coverage format won't let me use arbitrarily named coverage files anymore (I thought the `--format=` option exists exactly for this reason?), but it doesn't seem to work even if the file name is valid.

**Comment by afinetooth** [comment]
@mpatou @rouault @mrc0mmand We will deploy a fix for this shortly.

**Comment by Giorgi** [comment]
This has broken my builds too: 

![image](https://github.com/coverallsapp/coverage-reporter/assets/580749/215a6eb2-df2d-4ace-bcb5-d278826c2cef)

**Comment by afinetooth** [comment]
@Giorgi thanks for your report. Apologies for the inconvenience.

@mpatou @rouault [v0.6.12](https://github.com/coverallsapp/coverage-reporter/releases/tag/v0.6.12) of Coverage Reporter should fix this issue.

Let us know if it does not resolve your issue.

Thanks for your patience.

**Comment by afinetooth** [comment]
@mrc0mmand ^^

**Comment by afinetooth** [comment]
FWIW, here's how to use an earlier version of [Coverage Reporter](https://github.com/coverallsapp/coverage-reporter), if you encounter an issue like this again.

## If you are using [Coverage Reporter](https://github.com/coverallsapp/coverage-reporter) by itself  

In this case, `v0.6.9` would have been a good choice:

```
# v0.6.9

curl -L "https://github.com/coverallsapp/coverage-reporter/releases/download/v0.6.9/coveralls-linux.tar.gz" | tar -xz -C /usr/local/bin
coveralls report [...]
```

## If you are using Coverage Reporter via the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action)

You can pin the version of [Coverage Reporter]([Coverage Reporter](https://github.com/coverallsapp/coverage-reporter)) the action will use like this:

```
# v0.6.9

    - name: Coveralls Upload
      uses: coverallsapp/github-action@v2
      with:
        coverage-reporter-version: v0.6.9
```
