### ISSUE TITLE
Github action gateway timeout

### ISSUE THREAD

**Issue by csiefer2** [coverallsapp/coverage-reporter#136]
### What was wrong?

I'm using coveralls through a github action.  There are probably about ~50k gcov files that our testing generates.

We get finish the file processing and then this happens:

```
🚀 Posting coverage data to https://coveralls.io/api/v1/jobs
HTTP error:
---
Error: Gateway Time-out (504)
Message: <!DOCTYPE html>
```

### Logs

Coveralls version:    v0.6.12

**Comment by afinetooth** [comment]
Hi @csiefer2. Yes, this can happen with large C/C++ projects. [coverage-reporter](https://github.com/coverallsapp/coverage-reporter), which underlies our [github-action](https://github.com/coverallsapp/github-action), can process however many coverage report files you have in your environment, but above a certain number will lead to a timeout.

Our recommendation here is to use `gcov` to generate a single `lcov` report for your project (or at least _fewer_ reports).

You can find steps to do so in these blog posts / tutorials:

- [Code coverage testing of C/C++ projects using Gcov and LCOV](https://medium.com/@xianpeng.shen/use-gcov-and-lcov-to-perform-code-coverage-testing-for-c-c-projects-c85708b91c78)
- [Code Coverage Testing for C++](https://danielsieger.com/blog/2022/03/06/code-coverage-for-cpp.html)

By default, your `lcov` file will be exported as `coverage.info`, so if you think you'll have _any_ extraneous or duplicate files in your environment, we additionally recommend that you specify at least the `format`, and ideally, the `file` as well.

Those can be passed as a flag, and an argument, respectively, in the command line command for [coverage-reporter](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#usage).

For the **github-action**, you'll want to add those two [input options](https://github.com/marketplace/actions/coveralls-github-action#inputs). For example:

```
    - name: Coveralls Coverage Report Upload
      uses: coverallsapp/github-action@v2
      with:
        format: lcov
        file: path/to/coverage.info
```

**Comment by afinetooth** [comment]
@csiefer2 We did not hear back on this, so closing it in hopes that it's resolved. If not, please re-open or test again with the latest version of `coverage-reporter` (`v0.6.15`) and post a new issue. 🙏
