### ISSUE TITLE
Coverage reporter binary not working

### ISSUE THREAD

**Issue by gnsallman** [coverallsapp/coverage-reporter#145]
### What was wrong?
I'm using the [upload command in the coveralls orb](https://circleci.com/developer/orbs/orb/coveralls/coveralls?version=2.1.1#commands-upload) and I just started running into this error:

```
coveralls-linux.tar.gz: OK
Parsing args
Dry run - 0
Reporting coverage
+ ./coveralls report --no-fail
/bin/bash: line 75: ./coveralls: No such file or directory
```

**Comment by leemeichin** [comment]
Reproduced locally:

```bash
 wget -O co.tar.gz https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz
tar -xzvf co.tar.gz
```

File is called `coveralls-linux` and not `coveralls`

**Comment by afinetooth** [comment]
Hi @leemeichin , thanks for the report. We pulled that last release with the issue (`0.6.14`). We'll fix it and push it again later tonight.

**Comment by leemeichin** [comment]
Builds are running all good again, thanks :)

**Comment by afinetooth** [comment]
Thank you, @leemeichin!

**Comment by afinetooth** [comment]
For any new visitors, this issue is **resolved**, but I will leave it open for a while longer for anyone just discovering the error in their build logs today.

**Fix**:
The fix is to simply re-run your CI build. The next run should succeed and the version of coverage reporter shown in the output should be `v0.6.13`

**Comment by leemeichin** [comment]
thank you for the quick fix :) may I suggest that the github action is pinned to a version?

obviously that is more effort to maintain, but I would be happy to help with that.

**Comment by afinetooth** [comment]
@leemeichin good suggestion, thank you. In the meantime, in case you weren't aware, **you do have the ability to pin the version of coverage reporter with the GitHub Action**, so if you ever face this issue again, use the [input option `coverage-reporter-version`](https://github.com/marketplace/actions/coveralls-github-action#:~:text=coverage%2Dreporter%2Dversion,currently%20on%20macOS.) and pin to the last working version for you---the immediate previous version, most likely:

<img width="720" alt="Screenshot 2024-08-21 at 12 08 12 PM" src="https://github.com/user-attachments/assets/8bdec2a7-3a91-462c-893c-824054476b49">

**Comment by leemeichin** [comment]
Amazing, problem solved itself 😁 thanks!
