### ISSUE TITLE
What's up with the 0.6.14 release ?

### ISSUE THREAD

**Issue by jrfnl** [coverallsapp/coverage-reporter#149]
### Question

I've received notifications about this release three times now and every time I go to look for the release, I get a 404 page....

Looks like the release keeps getting janked, in which case, it is generally considered a good idea to tag a next release reverting the original release (and possibly clear our the release description and replace it with "release was pulled").

This prevents any automated systems getting confused (and potential dependabot updates which may have run between the release and it getting janked from becoming invalid).

**Comment by afinetooth** [comment]
@jrfnl apologies. I've been trying to cut a new release with cross-compiled linux binaries for `x86_64` and `aarch64`. I'm on a learning curve with several related subjects and have had to pull the release twice. (I'm pinch-hitting while we don't have anyone more senior to perform this task. Did not think it was going to be this challenging for me.) 

I wasn't aware of the follow-on effects. I just didn't want any releases out there with a binary that wouldn't work.

Best practice noted. Thanks for your patience.

**Comment by jrfnl** [comment]
@afinetooth No apologies needed. I just wanted to make sure that the effects of what was happening were known.

Kudos for persevering against the odds :+1:
