### ISSUE TITLE
v0.6.15 coveralls-checksums.txt has incorrect path prefix (`release/`)

### ISSUE THREAD

**Issue by adityasaky** [coverallsapp/coverage-reporter#165]
### What was wrong?

We noticed coverage runs via the github action failing because the path specified in the latest release's checksums file doesn't match the location of the binary in question. It looks like the latest release includes a `release/` prefix which isn't present in at the very least the last release.

### Logs

Our CI run is at https://github.com/gittuf/gittuf/actions/runs/11147824919/job/30983463583?pr=578#step:5:33

```
  mkdir -p ~/bin/
  cd ~/bin/
  if [ $COVERAGE_REPORTER_VERSION == "latest" ]
  then
    asset_path=latest/download
  else
    asset_path="download/${COVERAGE_REPORTER_VERSION}"
  fi
  curl -sLO "[https://github.com/coverallsapp/coverage-reporter/releases/${asset_path}/coveralls-linux.tar.gz](https://github.com/coverallsapp/coverage-reporter/releases/$%7Basset_path%7D/coveralls-linux.tar.gz)"
  curl -sLO "[https://github.com/coverallsapp/coverage-reporter/releases/${asset_path}/coveralls-checksums.txt](https://github.com/coverallsapp/coverage-reporter/releases/$%7Basset_path%7D/coveralls-checksums.txt)"
  cat coveralls-checksums.txt | grep coveralls-linux.tar.gz | sha256sum --check
  tar -xzf coveralls-linux.tar.gz
  rm coveralls-checksums.txt
  echo ~/bin >> $GITHUB_PATH
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    COVERAGE_REPORTER_VERSION: latest
sha256sum: release/coveralls-linux.tar.gz: No such file or directory
sha256sum: WARNING: 1 listed file could not be read
release/coveralls-linux.tar.gz: FAILED open or read
Error: Process completed with exit code 1.
```

**Comment by afinetooth** [comment]
@adityasaky Thanks for the report. We are working on it now. Will update you here.

**Comment by randseay** [comment]
+1 this is also affecting our team today.

```
Run mkdir -p ~/bin/
  mkdir -p ~/bin/
  cd ~/bin/
  curl -sLO https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz
  curl -sLO https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-checksums.txt
  cat coveralls-checksums.txt | grep coveralls-linux.tar.gz | sha[2](https://github.com/dispel/dispel/actions/runs/11148756317/job/30986336387#step:6:2)56sum --check
  tar -xzf coveralls-linux.tar.gz
  rm coveralls-checksums.txt
  echo ~/bin >> $GITHUB_PATH
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
sha256sum: release/coveralls-linux.tar.gz: No such file or directory
release/coveralls-linux.tar.gz: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
Error: Process completed with exit code 1.
```

**Comment by afinetooth** [comment]
## Workarounds for now

### Suggestion for users of coverage-reporter directly:

Download and install the latest working version (`v0.6.14`)

```
curl -L https://github.com/coverallsapp/coverage-reporter/releases/download/v0.6.14/coveralls-linux.tar.gz | tar -xz -C /usr/local/bin
```

#### Suggestion in meantime for users of the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action):

set [fail-on-error input option](https://github.com/marketplace/actions/coveralls-github-action#:~:text=fail%2Don%2Derror,to%20any%20errors.) to `false` for now:

```
fail-on-error: false
```

#### For the [Coveralls Orb for CircleCI](https://circleci.com/developer/orbs/orb/coveralls/coveralls):

set [fail_on_error input option](https://circleci.com/developer/orbs/orb/coveralls/coveralls#:~:text=boolean-,fail_on_error,-Whether%20to%20fail) to `false` for now:

```
fail_on_error: false
```

**Comment by afinetooth** [comment]
@adityasaky We believe we've patched this for now by updating the `coveralls-checksums.txt` file. 

Can you please try `v0.6.15` again to see if it works for you now?

**Comment by adityasaky** [comment]
Looks good! https://github.com/gittuf/gittuf/actions/runs/11147824919/job/30988431835

**Comment by afinetooth** [comment]
Awesome. Thank you! ❤️ 

We're now fixing the issue for subsequent releases.

**Comment by afinetooth** [comment]
Root cause analysis (by user request) [here](https://github.com/coverallsapp/github-action/issues/224#issuecomment-2389467014).
