### ISSUE TITLE
Add way to specify coverage file format

### ISSUE THREAD

**Issue by kevinoid** [coverallsapp/coverage-reporter#36]
### :zap: Summary

It would be great if the coverage reporter had a way to specify the format of the coverage file, rather than relying on detection from the filename.

### Background

After upgrading from `coverallsapp/github-action@v1` to `coverallsapp/github-action@v2` my .NET projects which use [coverlet](https://github.com/coverlet-coverage/coverlet) to produce coverage results in lcov format fail to upload the coverage to coveralls with an error similar to the following:

> ⚠️ Coverage reporter does not yet know how to process this file: NetCoreProject.UnitTests/TestResults/a4c52cc8-0a0c-4d2e-aacd-e6aa12cdeef6/coverage.info

Example [with v1](https://github.com/kevinoid/NetCoreProject/actions/runs/4394063882) and [with v2](https://github.com/kevinoid/NetCoreProject/actions/runs/4435134707/jobs/7781909366).

This occurs because `coverage.info` does not match the [filename patterns coverage-reporter expects](https://github.com/coverallsapp/coverage-reporter/blob/v0.2.13/src/coverage_reporter/parsers/lcov_parser.cr#L15-L22).  Unfortunately, it's not possible to change the name produced by coverlet (see https://github.com/coverlet-coverage/coverlet/issues/1276 ) so an extra build step is currently required to rename `coverage.info` to `lcov.info` to satisfy coverage-reporter.  It would be great if there were a way to avoid this hassle.

**Comment by mrexox** [comment]
Hey! Thank you for the issue. I've recently released a new version of coverage-reporter and updated Github action `v2` tag. Now you can specify `format: lcov`, and the reporter should use it to parse the report.

Now this setup should work:
```yml
- uses: coverallsapp/github-action@v2
  with:
    file:  NetCoreProject.UnitTests/TestResults/a4c52cc8-0a0c-4d2e-aacd-e6aa12cdeef6/coverage.info
    format: lcov
```

Please, feel free to reopen this issue or open a new one if you face any problems.

**Comment by kevinoid** [comment]
Looks perfect!  Thanks for the lightning-fast fix @mrexox!
