### ISSUE TITLE
Problems with paths

### ISSUE THREAD

**Issue by jnyrup** [coverallsapp/coverage-reporter#44]
### What was wrong?

When trying to upgrading to `coverallsapp/github-action@v2` the paths on coveralls.io are not mapping to the source files.
Since v2 changed to this project I'm guessing that this is the right place to report, please let me know if I'm wrong about that.

Is this the problem described in #41?

From the logs shown below I'm guessing the paths might need to converted into POSIX paths when running on Windows?

### Logs

v1.1.3
https://coveralls.io/builds/58262714/source?filename=Src%2FFluentAssertions%2FFluentActions.cs
![image](https://user-images.githubusercontent.com/919634/227962699-c0ab62d2-2976-4fa6-824a-47aca6c3f4c0.png)
output from node-coveralls
`cat .\TestResults\reports\lcov.info | coveralls -v`
```json
"source_files": [{
    "name": "Src/FluentAssertions/AggregateExceptionExtractor.cs",
```

v0.2.17
[github-actions](https://github.com/jnyrup/fluentassertions/actions/runs/4526476453/jobs/7971672729)
[uploaded lcov-file](https://github.com/jnyrup/fluentassertions/suites/11818829540/artifacts/617161403)

https://coveralls.io/builds/58241348/source?filename=%5CSrc%5CFluentAssertions%5CFluentActions.cs
![image](https://user-images.githubusercontent.com/919634/227962518-763191d8-e2cd-43e7-a955-b9537623cf37.png)
output from coverage-reporter
`coveralls-windows.exe -r [token] --dry-run --debug .\lcov.info`
```json
"source_files": [
  {
    "name": "C:\\dev\\fluentassertions\\Src\\FluentAssertions\\AggregateExceptionExtractor.cs",
```

**Comment by jnyrup** [comment]
Running CI on Windows does not work
https://coveralls.io/builds/58476950/source?filename=%5CSrc%5CFluentAssertions%5CExecution%5CDefaultAssertionStrategy.cs
![image](https://user-images.githubusercontent.com/919634/229314589-b7c860af-18d4-43f1-b8dd-2cf0c2c8bf9a.png)


Running CI on Linux works
https://coveralls.io/builds/58477085/source?filename=Src%2FFluentAssertions%2FExecution%2FDefaultAssertionStrategy.cs
![image](https://user-images.githubusercontent.com/919634/229314581-3b9cb87a-6110-4d98-ae79-6700b529fdab.png)

**Comment by mrexox** [comment]
Hey! Thank you for the issue! There is indeed a [path transformation](https://github.com/nickmerwin/node-coveralls/blob/master/lib/convertLcovToCoveralls.js#L39) in node-coveralls. I've tried to implement a similar approach in coverage-reporter. Unfortunately I don't have a Windows machine to test it. I'll appreciate if you could provide some feedback after I release this fix.

**Comment by mrexox** [comment]
@jnyrup, a fix is available now. If you use github action v2 or download a binary from the latest release, it should use the fixed version.

Please, come back with any feedback :)
