### ISSUE TITLE
PHPUnit's clover format

### ISSUE THREAD

**Issue by szepeviktor** [coverallsapp/coverage-reporter#53]
### Supporting clover format

Hello! PHPUnit has millions of users.
https://docs.phpunit.de/en/10.0/configuration.html#the-report-element

Can coverage-reporter read clover XML files?

**Comment by mrexox** [comment]
Hey @szepeviktor! Right now coverage-reporter doesn't support clover XML reports but we are planning to add the support for it. If you want to speed it up, could you please share a repo I can use for testing (to create clover coverage report and parse it)? I'd appreciate it a lot.

**Comment by afinetooth** [comment]
@szepeviktor thanks for reaching out about this. 
I believe Clover XML was next on our list of formats to add support for.

On that topic, though, I want to take the opportunity to point out that if anyone, including yourself, is willing to contribute a **new format parser**&mdash;_per [this message in the project README](https://github.com/coverallsapp/coverage-reporter#:~:text=You%20can%20add%20a%20report%20parser%20to%20this%20project%20by%20following%20these%20instructions.), which links to our [Developer Guide for adding a new format parser](https://github.com/coverallsapp/coverage-reporter/blob/master/doc/development.md#add-coverage-format-support)_&mdash;Coveralls is offering compensation in the form of **one or more months of free service at Coveralls.io**.

The same goes for supporting new [CI services](https://github.com/coverallsapp/coverage-reporter#supported-ci-services), which is pretty straighforward if you look at the [currently supported CI modules here](https://github.com/coverallsapp/coverage-reporter/tree/master/src/coverage_reporter/ci), and our [docs on CI env vars](https://docs.coveralls.io/ci-services#option-1-use-common-environment-variables).

Thanks 🙏
