### ISSUE TITLE
Failures in Github Actions after v0.3.8 was released

### ISSUE THREAD

**Issue by ogenstad** [coverallsapp/coverage-reporter#65]
### What was wrong?

Yesterday our CI pipelines started to fail and it seems to have happened just after v0.3.8 was released.

### Logs

This is from a private repo but let me know if you need any additional information. The coverage files comes from Python.

```
Run coverallsapp/github-action@v2.0.0
Run curl -sL https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz | tar xz -C /usr/local/bin
Run coveralls    
 
⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠀⠀⠀⣼⣿⣧⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀⢠⣿⣿⣿⠿⣿⣿⣿⡄⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀⠀⠀
 
  v0.3.8

🔍 Detected coverage file: coverage.xml
🔍 Detected coverage file: .coverage
Oops! Regex match error: UTF-8 error: byte 2 top bits not 0x80
Coveralls Coverage Reporter v0.3.8
Error: Process completed with exit code 1.
```

**Comment by mrexox** [comment]
Hey! Thank you for the issue. I am going to fix it as soon as possible. The reason is probably the upgrade of Crystal version (1.7.2 -> 1.8.1, and it uses pcre2, which raises such an error). I'll notify you when I release a fix.

**Comment by mrexox** [comment]
I've just release v0.3.9 with a version downgrade. Please, rerun the failing workflow in your CI. Everything should work correctly now.

**Comment by ogenstad** [comment]
Thank you, it's working again!
