### ISSUE TITLE
Does this orb support the coveralls or coveralls+ formats?

### ISSUE THREAD

**Issue by josegonzalez** [coverallsapp/coverage-reporter#71]
### Question

Does this orb support the coveralls or coveralls+ formats? From reading the readme/source, it seems like no, but I just want to be sure.

**Comment by mrexox** [comment]
No, currently it doesn't support coveralls/coveralls+ formats. But I am interested in adding the support for them. Can you share the tools you use to generate reports in these formats? It would be helpful.

**Comment by josegonzalez** [comment]
I am using [grcov](https://github.com/mozilla/grcov) for a rust-based program to generate those reports. I'm migrating from the old version of the coveralls orb that supports a node project for those formats, and wanted to see if maybe switching from lcov would fix my parsing issues.

**Comment by mrexox** [comment]
I have added the support for `coveralls` format of grcov: https://github.com/coverallsapp/coverage-reporter/pull/79. It will be available with the v0.4.3 release.

**Comment by josegonzalez** [comment]
Should it also support coveralls+ (I don't know what the difference is tbh).

**Comment by mrexox** [comment]
I've read the code for `coveralls+` format - it adds `functions` field, but I'm afraid it doesn't get processed by Coveralls now. Maybe it was a few years ago (the code for coveralls+ format is written 6 years ago btw). So, basically coveralls+ adds nothing really special.

**Comment by josegonzalez** [comment]
Thanks for the response!
