### ISSUE TITLE
ArgumentError: Invalid Int64: "18446744073709551615" when parsing lcov file

### ISSUE THREAD

**Issue by josegonzalez** [coverallsapp/coverage-reporter#72]
### What was wrong?

I switched from the 1.0.6 version of the Coveralls CircleCI Orb to the latest 2.1.1 version and started getting the above in my CI jobs.  The new orb uses this project instead of the old node-coveralls project.

It appears that because the parsing of the file uses an Int64 for something (not sure what tbh), it fails to parse some number.

### Logs

```
coveralls-linux.tar.gz: OK
Parsing args
Dry run - 0
Reporting coverage
+ ./coveralls --file /root/repo/lcov-app.info --format lcov
 
⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠀⠀⠀⣼⣿⣧⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀⢠⣿⣿⣿⠿⣿⣿⣿⡄⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀⠀⠀
 
  v0.3.9

✏️ Forced coverage format: lcov
📄 Using coverage file: /root/repo/lcov-app.info
Could not process tracefile: /root/repo/lcov-app.info
ArgumentError: Invalid Int64: "18446744073709551615"
```

**Comment by mrexox** [comment]
Hey! Could you send the `lcov-app.info`, please, so I could check what is being parsed? There might be an edge case I haven't taken into account.

**Comment by mrexox** [comment]
Hey @josegonzalez, can you share your `lcov-app.info`, please?

**Comment by josegonzalez** [comment]
Yes I can! Is there some way I can send it to you securely? I don't know if this will include code information from the codebase and it's from a private repository.

**Comment by mrexox** [comment]
For sure, my email is valentin@coveralls.io

**Comment by josegonzalez** [comment]
I sent a Gdrive attachment from jdiazgonzalez@watchful.io.

**Comment by mrexox** [comment]
Thank you! Your report helped me to figure out the issue. Please check v0.4.6 version!
